version: '3.8'

services:
  api-gateway:
    build: ./gateway
    ports:
      - "3000:3000"
    environment:
      - MONGO_URL=mongodb://mongodb:27017/whatsapp
    depends_on:
      - mongodb
  #      mongodb:
  #        condition: service_healthy

  mongodb:
    image: mongo:6.0
    restart: always
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db
#    healthcheck:
#      test: ["CMD-SHELL", "mongosh --eval 'db.runCommand({ ping: 1 })' --quiet"]
#      interval: 10s
#      timeout: 10s
#      retries: 10

  auth-service:
    build: ./services/auth-service
    ports:
      - "3001:3001"
    environment:
      - MONGO_URL=mongodb://mongodb:27017/whatsapp
    depends_on:
      - mongodb
      - api-gateway
#      mongodb:
#        condition: service_healthy

volumes:
  mongo_data: