version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    restart: always
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db
    # Uncomment to enable healthcheck
    # healthcheck:
    #   test: ["CMD-SHELL", "mongosh --eval 'db.runCommand({ ping: 1 })' --quiet"]
    #   interval: 10s
    #   timeout: 10s
    #   retries: 10

  auth-service:
    build: ./services/auth-service
    ports:
      - "3001:3001"
    environment:
      - DB_URL=mongodb://mongodb:27017/whatsapp
      - JWT_SECRET=your_super_secret_key
    depends_on:
      - mongodb
      - api-gateway
    # Uncomment to enable healthcheck
    # healthcheck:
    #   test: ["CMD-SHELL", "curl -f http://localhost:3001/ || exit 1"]
    #   interval: 10s
    #   timeout: 10s
    #   retries: 10

  api-gateway:
    build: ./gateway
    ports:
      - "3000:3000"
   
    depends_on:
      - mongodb

volumes:
  mongo_data: