version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    restart: always
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db

  auth-service:
    build:
      context: .
      dockerfile: services/auth-service/Dockerfile
    ports:
      - "3001:3001"
    environment:
      - DB_URL=mongodb://mongodb:27017/whatsapp
      - JWT_SECRET=your_super_secret_key
    depends_on:
      - mongodb
    restart: always

  main-service:
    build: ./services/main-service
    ports:
      - "3002:3002"
    environment:
      - DB_URL=mongodb://mongodb:27017/whatsapp
      - JWT_SECRET=your_super_secret_key
    depends_on:
      - mongodb
    restart: always

  api-gateway:
    build: ./gateway
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
      - auth-service
      - main-service
    restart: always

volumes:
  mongo_data:
